### PR TITLE
TPU support

### LINKED ISSUE #102: TPU
Does this code work on TPU?

### PR DESCRIPTION
**Pull request by carmocca**
Part of #102

Commands on a gcloud v4-8 instance:

```python
git clone https://github.com/Lightning-AI/lit-llama
cd lit-llama
git checkout carmocca/tpu-inference
pip install -r requirements.txt
pip uninstall fastapi -y; pip install fastapi
python3 scripts/download.py --repo_id huggyllama/llama-7b
python3 scripts/convert_hf_checkpoint.py

export PJRT_DEVICE=TPU
python3 generate.py --prompt "Hello, my name is"
```

Logs for generate.py (with #174 merged)
```shell
Time to load model: 7.19 seconds.
Global seed set to 1234
Hello, my name is John and my family and I live in a beautiful house on the outskirts of the town in which we are at the moment. My parents and I live together in one house as we are not separate from each other. We are a small
Time for inference: 753.78 sec total, 0.07 tokens/sec
```

### CODE REVIEW

**Comment by lantiga** [comment]
@t-vi is getting back to real RoPE, hopefully that will solve the issue with `view_as_complex` and `view_as_real`

**Comment by carmocca** [comment]
I let it run for ~10 minutes and when I killed the command, it was still at

```python
  File "/home/carmocca/lit-llama/lit_llama/model.py", line 230, in apply_rope
    xc = torch.view_as_complex(x.float().reshape(*x.shape[:-1], -1, 2))
```

So it seems like it's so slow on CPU it's unusable. It'll have to wait for that replacement. I'll merge that PR into this one to try it out

**Comment by lantiga** [comment]
Sounds great.
Looks like #174 is a go in any case.

**Comment by carmocca** [comment]
It worked!

**Comment by awaelchli** [comment]
@carmocca In your output I see

> Time for inference: 753.78 sec total, 0.07 tokens/sec

We need to look into that 😅 You are sure that it actually detected and ran on the TPU cores?

**Review by awaelchli — APPROVED** [review]

**Comment by lantiga** [comment]
> @carmocca In your output I see
> 
> > Time for inference: 753.78 sec total, 0.07 tokens/sec
> 
> We need to look into that 😅 You are sure that it actually detected and ran on the TPU cores?

Did switching to real help with this? It should right?

**Review by lantiga — APPROVED** [review]

**Comment by lantiga** [comment]
Amazing! What about a quick howto? :-)

**Comment by carmocca** [comment]
No, that's just the output of the script as-is. Let me try that now

**Comment by t-vi** [comment]
So I know nothing about TPU but back in my mind, I am thinking I recall hearing fp16 is not its friend. I am not sure what to do about the rope cache there, as keeping the cache in anything but fp16 seemed to be a large headache. If TPU can to fp32, we might cast the cache to fp16 to truncate and then to fp32.

**Comment by t-vi** [comment]
(Also, of course, if it is shape specific, it'll have the same issue as torch.compile, triton etc.)

**Comment by carmocca** [comment]
Here's the results after warmup, using the code in #178 

```python
Time for generation 0: 755.14 sec total, 0.07 tokens/sec
Time for generation 1: 11.52 sec total, 4.34 tokens/sec
Time for generation 2: 11.09 sec total, 4.51 tokens/sec
Time for generation 3: 11.37 sec total, 4.40 tokens/sec
```

**Comment by carmocca** [comment]
Dumping here my debugging:

With bfloat16 or float16, I get

```python
  File "generate.py", line 160, in <module>
    CLI(main)
  File "/home/carmocca/.local/lib/python3.8/site-packages/jsonargparse/cli.py", line 82, in CLI
    return _run_component(component, cfg_init)
  File "/home/carmocca/.local/lib/python3.8/site-packages/jsonargparse/cli.py", line 138, in _run_component
    return component(**cfg)
  File "generate.py", line 131, in main
    y = generate(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "generate.py", line 52, in generate
    logits = model(idx_cond.view(1, -1))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carmocca/lightning/src/lightning/fabric/wrappers.py", line 110, in forward
    output = self._forward_module(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carmocca/lit-llama/lit_llama/model.py", line 67, in forward
    x = block(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carmocca/lit-llama/lit_llama/model.py", line 88, in forward
    x = x + self.attn(self.rms_1(x))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carmocca/lit-llama/lit_llama/model.py", line 121, in forward
    self.rope_cache = build_rope_cache(
  File "/home/carmocca/lit-llama/lit_llama/model.py", line 201, in build_rope_cache
    seq_idx = torch.arange(seq_len, dtype=dtype, device=device)
RuntimeError: std::bad_alloc
```

**Pull request merged**
